### ISSUE TITLE
Playback crashes when resuming after pausing video for 5 minutes

### ISSUE THREAD

**Issue by tuxrinku** [jellyfin/jellyfin-kodi#466] opened 2021-02-01 21:22 UTC
**Describe the bug**
I can play any file without any problem, but when I pause in a middle of a video for like 5 or 10 minutes, the playback crashes when I resume and I have to wait another 5 minutes (or quit and restart kodi) before being able to launch the video again.

**To Reproduce**

1. Play any movie or TV show
2. Pause in the middle of it for 5 minutes
3. Resume playback 
4. The video will stop after ~10 seconds

**Expected behavior**
No playback stop after resuming

**Logs**
Kodi doesn't create any logs since it's not really a kodi crash, but I'll take a look at kodi general logs or jellyfin logs

**System (please complete the following information):**
 - OS: Ubuntu 20.10
 - Jellyfin Version: 10.6.4
 - Kodi Version: 18.9
 - Addon Version: 0.7.0
 - Playback Mode: Add-on

**Comment by mcarlton00** [comment] 2021-02-11 23:21
You're able to find logs at `/home/tuxrinku/.kodi/temp/kodi.log`.  Alternatively, you can upload them using this https://kodi.wiki/view/Log_file/Easy

**Comment by tuxrinku** [comment] 2021-03-02 19:33
Sorry for the delay. I stumbled upon a similar error. When I open an episode right after the previous ended (let's say within 30 seconds), it doesn't load. If I wait like 2-3 minutes after the previous episode ended, it works without any problem. log attached below.
[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/6071257/kodi.log)

**Comment by mcarlton00** [comment] 2021-03-08 03:28
Just as another datapoint, I left a show paused for over 24 hours this weekend and it picked up and finished playing fine.  The only issue with it was that it had stopped reporting progress to the server so it wasn't showing in the active sessions in the server dashboard, but it still properly reported watched status when the file finished.

**Comment by tuxrinku** [comment] 2021-03-10 20:46
I switched to the native mode, and everything is good now. So the issue seems to be exclusive to the add-on mode.

**Comment by mcarlton00** [comment] 2021-07-10 00:35
Unfortunately, I've never been able to replicate this.  And since the issue isn't directly affecting you anymore, I'm going to go ahead and close this

**Closed by mcarlton00** 2021-07-10 00:35 UTC

**Comment by ChessHere** [comment] 2022-01-19 18:38
Member
 0
 1
Posted 12 minutes ago
Hi all. Posting this cuz I literally spent days on this issue and thought I might be able to help others with this miserable issue. Kodi freezes with blue buffer circle at 100 - sometime with regular playback but almost always with resume or fast forward or backward. Tried umpteen fixes - advancedsettings parameters, cache settings, buffer modes, reading modes, switching between full screen and windowing. adjusting win10 parameters, nvidia graphics card parameters - nothing worked. Finally I found an advancedsettings.xml parameter that fixed the freezing 99% of the time. Turns out this network parameter "<nfstimeout>30</nfstimeout>" did the trick (Kodi 19 defaults to only 5 seconds - not sure if higher than 30 works but I only needed 30). I have 16 gb so I set cache to highest limit acceptable not sure I needed to but didn't hurt. Here is the full script I used for the AdvancedSettings.xml file - hope it helps you:

<advancedsettings>
<cache>
<buffermode>1</buffermode>
<memorysize>314572800</memorysize>
<readfactor>15</readfactor>
</cache>
<nfstimeout>30</nfstimeout>
</advancedsettings>
 

Good Luck...

**Comment by ChessHere** [comment] 2022-01-19 19:00
hmmm... new to this site - the xml code was stripped out. I used the nfstimeout parameter and set it to 30.  the full code can be found on a posting I put on this site...https://emby.media/community/index.php?/forum/99-kodi/

**Comment by mcarlton00** [comment] 2022-01-19 19:27
I'm going to copy the XML here so it's easily findable in case anybody else has the issue:

```
<advancedsettings>
  <cache>
    <buffermode>1</buffermode>
    <memorysize>314572800</memorysize>
    <readfactor>15</readfactor>
  </cache>
  <nfstimeout>30</nfstimeout>
</advancedsettings>
```

**Comment by justlogit** [comment] 2023-07-29 09:38
I have the same problem with v19 and 20beta on androidtv11 tv box.
