### ISSUE TITLE
Suggestion: submitted jellyfin to official kodi plugin repo

### ISSUE THREAD

**Issue by frankyifei** [jellyfin/jellyfin-kodi#234] opened 2020-03-18 05:20 UTC
as the title says, it is much easier to upgrade in this way.

**Comment by TrueTechy** [comment] 2020-03-18 05:45
Because of the way the addon directly modifies the kodi database to insert the media into it we are prohibited from being added to the official repo, hence we have our own. With the new media importing capabilities kodi 19 is supposed to have we might be able to use that instead which would allow us to use the official repo but for now it is not possible

**Comment by TrueTechy** [comment] 2020-03-18 05:47
Duplicate of #187

**Closed by TrueTechy** 2020-03-18 05:47 UTC
Labels: duplicate
