### ISSUE TITLE
"Mark as watched" not synced

### ISSUE THREAD

**Issue by random-human-being** [jellyfin/jellyfin-kodi#606] opened 2022-01-14 12:30 UTC
**Describe the bug**
"Mark as watched" from the context menu is not synced with the server.

**To Reproduce**
1. Pick a random film or episode and watch it to about halfway through, then stop it
2. Verify that both Kodi and Jellyfin now show it as in progress with the same timestamp
3. From Kodi, open the context menu and select "Mark as Watched" without playing the content a second time
4. Now Kodi should have marked it as watched, however on the server it still show up as in progress with the previous timestamp. Forcing a full library sync from the Kodi add-on will also revert its status to the one on the server, rather than updating the latter

**Expected behavior**
When selecting "mark as watched" from the context menu in Kodi, its status is synced with the server.

**Logs**
No errors in the logs as far as I can tell, either Kodi's or the server's.

**System (please complete the following information):**
 - OS: LibreElec (both x86 and RPi), FireTV
 - Jellyfin Version: various, from 10.7.x to 10.8.0-alpha2 (official Docker image)
 - Kodi Version: various, 18.x and 19.x
 - Addon Version: 0.7.6 and 0.7.7
 - Playback Mode: Add-On

**Comment by mcarlton00** [comment] 2022-03-09 21:50
I can't replicate this.  I saw the update immediately on the server, and then received the following message _from_ the server indicating the userdata was changed and Kodi should update it's database if it hasn't already.

```
INFO::jellyfin_kodi/entrypoint/service.py:249 [ UserDataChanged ] {'UserDataList': [{'IsFavorite': False, 'ItemId': 'e7f946a60673125405426c56007a4540', 'Key': '82992', 'LastPlayedDate': '2022-03-09T21:44:51.4576621Z', 'PlayCount': 1, 'PlaybackPositionTicks': 0, 'Played': True}, {'IsFavorite': False, 'ItemId': 'e1c314100ec3cf42fb97cd0da6ecffe4', 'Key': 'e1c31410-0ec3-cf42-fb97-cd0da6ecffe4', 'PlayCount': 0, 'PlaybackPositionTicks': 0, 'Played': False, 'UnplayedItemCount': 4}], 'UserId': '2e46fa0e186f4472a3af7f2eb0eb4ffe'}
```

I've tried marking as watched and unwatched in both Kodi and the server and it appears to be working correctly in both directions.

**Comment by random-human-being** [comment] 2022-03-11 17:47
Is this from the server log when using the latest alpha?

**Comment by mcarlton00** [comment] 2022-03-11 18:35
That line is from the Kodi logs.

What happens is we mark something as watched/unwatched, that gets reported to the server as a http post request, and then the server sends out a broadcast to websocket connected clients with information about what was just changed.  So this is the message the server sends out as a result of the server receiving our mark as watched update.  In our case since it's already updated locally, there's no change that needs to happen, but if you have multiple Kodi clients this is how it would be synchronized to them at the same time.

**Comment by random-human-being** [comment] 2022-03-14 16:41
That line doesn't seem to appear in my log when I do that. It _does_ appear when I watch the episode and/or stop watching it (and the watched status on the server is updated accordingly). However after selecting "Mark as watched" all I get is the following:
```

2022-03-14 16:34:44.231 T:9101     INFO <general>: CActiveAESink::OpenSink - initialize sink
2022-03-14 16:34:44.233 T:9101     INFO <general>: Trying to open: samplerate: 44100, channelMask: 12, encoding: 4
2022-03-14 16:34:44.247 T:9101     INFO <general>: CAESinkAUDIOTRACK::Initializing with: m_sampleRate: 44100 format: AE_FMT_FLOAT (AE) method: PCM stream-type: PCM-STREAM min_buffer_size: 60208 m_frames: 1881 m_frameSize: 8 channels: 2
2022-03-14 16:34:46.073 T:9156     INFO <general>: JELLYFIN.jellyfin_kodi.monitor -> DEBUG::jellyfin_kodi/monitor.py:91 [ xbmc: VideoLibrary.OnUpdate ] {
                                                       "item": {
                                                           "id": 1454,
                                                           "type": "episode"
                                                       },
                                                       "playcount": 1
                                                   }
2022-03-14 16:34:46.094 T:9156     INFO <general>: JELLYFIN.jellyfin_kodi.objects.actions -> INFO::jellyfin_kodi/objects/actions.py:720  [ update/1 ] kodi_id: 1454 media: episode
2022-03-14 16:34:46.134 T:9156     INFO <general>: JELLYFIN.jellyfin_kodi.database -> DEBUG::jellyfin_kodi/database/__init__.py:60 --->[ database: jellyfin ] 2584174520
2022-03-14 16:34:46.286 T:9156     INFO <general>: JELLYFIN.jellyfin_kodi.database -> DEBUG::jellyfin_kodi/database/__init__.py:172 ---<[ database: jellyfin ] 2584174520
2022-03-14 16:34:46.316 T:9156     INFO <general>: JELLYFIN.jellyfin_kodi.helper.utils -> DEBUG::jellyfin_kodi/helper/utils.py:56 --[ window clear: jellyfin.skip.30d3a9c82e9146accf9d8288ea9ddc83 ]
```

**Comment by mcarlton00** [comment] 2022-04-02 23:06
This is using Kodi on linux, tried both versions 19.3 and 19.4.  Also tested against server versions 10.7.7 and 10.8.0:alpha5 (beta1 is out now, but I haven't gotten to that yet)

**Comment by iKeule257** [comment] 2022-04-11 17:48
I am running OSMC on a Vero 4K+ and I also experience the same problem. Selecting "Mark as watched" from the Kodi context menu does not sync the watched status to the server.

**Comment by iKeule257** [comment] 2022-04-11 19:51
Something weird happened. I did install Kodi and Jellyfin for Kodi on a Windows PC. On that PC, marking as watched synced to the server as expected. After that I tried on my Vero again, and it suddenly also worked there. Have to do some further testing.

**Comment by random-human-being** [comment] 2022-12-17 16:27
I'm not sure what changed since I opened this issue, but as of a few weeks ago I noticed everything started working properly.
Whatever you changed, thank you.

**Closed** 2022-12-17 16:27 UTC
Labels: bug

**Comment by sic6SaNdMaN** [comment] 2024-11-22 13:48
I would like to see this issue reopened, because I have this problem as well.
I can reproduce it on all my devices and Kodi installations and it's going on for at least a year now. I hoped, it will get fixed.
And it didn't bother me that much, because normally I watch an episode nearly to it's end, so it will be recognized as "watched".
But now I have several series, where there are 5 minutes or more of endcredits and  I skip them, of course.
So every episode stays as "partially watched".

And that's the important point: Basis is a "partially watched" episode or film.
When I now use "mark as watched" in Kodi, this doesn't get synced to the Jellyfin server.
Same goes for "reset position" (I don't know the exact english label for it), that doesn't reach the server either.

The only thing that works and gets synced is
- first "mark as unwatched"
- then "mark as watched" again.

This is my workaround and has been for a long time.
But doing this on every episode is kinda annoying...

Infos:
Jellyfin server on RPi4B:
Server-Version 10.9.10
Web-Version 10.9.10
Build-Version 10.9.10

Kodi on Nvidia Shield:
Kodinerds Omega 21.1 (mainly used)
Kodinerds Nexus 20.5

Kodi on Sony Bravia Android TV:
Kodinerds Omega 21.1

Kodi on LibreELEC 11.0.6:
Kodi Nexus 20.3

This behaviour can be reproduced on all of these boxes/installations.

I'm happy to provide logs, screenshots or whatever.

**Comment by oddstr13** [comment] 2024-11-22 14:56
There is *at least* one open issue about this right now, so I don't see any reason to reopen this specific one
