### ISSUE TITLE
Jellyfin to Kodi not syncing

### ISSUE THREAD

**Issue by docfactory37** [jellyfin/jellyfin-kodi#105] opened 2019-10-03 09:51 UTC
When doing a fresh install library's not syncing 

no option to add library's 

Tested on Android version 5 is and Android tv box and 10 is pixel 3

Jellyfin to Kodi version 3.2

Have try new install on 2 device s and same issue

![Screenshot_20191003-194317](https://user-images.githubusercontent.com/20963053/66117057-2facc980-e617-11e9-9e7f-c57037b6a080.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: [e.g. Android, Debian, Windows]
 - Jellyfin Version: [e.g. 10.0.1]
 - Kodi Version: [e.g. 18.3]
 - Addon Version: [e.g. 0.2.1]

**Additional context**

**Comment by mcarlton00** [comment] 2019-10-03 12:28
Duplicate of #97.  It's been fixed in master, but we haven't gotten a new release pushed out yet

**Closed by mcarlton00** 2019-10-03 12:28 UTC
