### ISSUE TITLE
Would it be possible to make Jellyfin for Kodi compatible with dkanada's intro plugin ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#609] opened 2022-01-20 23:18 UTC
Not really a bug, more of a suggestion.

I would like to use this addon for Jellyfin, which allows to add a custom intro for every video:
https://github.com/dkanada/jellyfin-plugin-intros

It works great when playing from Jellyfin web ui or from Jellyfin Media Player.

But it doesn't work with Jellyfin for Kodi. When the plugin is installed and configured, Jellyfin for Kodi addon will play the custom intro file, but will not play the following movie or episode. It stops the playback like the episode has ended.

Would it be possible to detect that multiple files are queued (when using the intro plugin) and play them all instead of only the 1st file (the intro) ? That would make Jellyfin for Kodi compatible with Intro Plugin.

Thanks in advance for any answer,
Have a great day

**Comment by mcarlton00** [comment] 2022-01-21 02:35
It should be possible, yes.  It should already be working now, but it's apparently been broken for a while and nobody has had time to debug it yet.  Duplicate of #549

**Closed by mcarlton00** 2022-01-21 02:35 UTC
Labels: duplicate
