### ISSUE TITLE
first item in playlists registereds but next items in list does not

### ISSUE THREAD

**Issue by bwaddington** [jellyfin/jellyfin-kodi#259] opened 2020-03-09 17:43 UTC
Server: Jellyfin
Version: 10.5.0
Operating System: Linux
Architecture: X64

the play lists are now being sent to kodi and will all play also when starting at like s02e5 starts from there but the first item in the playlists registereds as being play but from there on next items in list does not registereds as being played

tried kodi 0.4.1, kodi 0.5.0, kodi 0.5.1 so i dont think its kodi fault

**Comment by JustAMan** [comment] 2020-03-31 21:13
Moving to Kodi repository.

**Comment by mcarlton00** [comment] 2020-03-31 21:50
Duplicate of #198

**Closed by mcarlton00** 2020-03-31 21:50 UTC
Labels: bug, duplicate
