### ISSUE TITLE
Occasional crashes on Pi 3

### ISSUE THREAD

**Issue by random-human-being** [jellyfin/jellyfin-kodi#423] opened 2020-11-14 22:52 UTC
**Describe the bug**
Kodi occasionally (around twice a week?) freezes completely. This has happened ever since I've installed Jellyfin (client and server are on the same device). Before that, it worked without issues

**To Reproduce**
It doesn't really happen with any consistency. Occasionally standard x264/AC3 videos will completely freeze, making Kodi and the Jellyfin server completely unresponsive. This doesn't seem to be affected by bitrate

**Logs**
I couldn't figure out which lines where exactly showing an error, or really anything that could make the system crash. This specific two, however, are repeated almost every second in the 30 minutes before the crash:
```
2020-11-14 21:26:12.004 T:1495237504  NOTICE: JELLYFIN.helper.utils -> DEBUG::jellyfin_kodi/helper/utils.py:145 ---[ event: plugin.video.jellyfin/ReportProgressRequested ] "[{\"Report\": false}]"
2020-11-14 21:26:12.141 T:1495237504  NOTICE: JELLYFIN.monitor -> DEBUG::jellyfin_kodi/monitor.py:97 [ plugin.video.jellyfin: ReportProgressRequested ] {
                                                "Report": false
```
The whole log, in debug mode, is 65MB, so I've uploaded it to a file host: https://files.catbox.moe/mdxs5b.log

Here's also the log from the Jellyfin server, should it be of use: https://pastebin.com/RAAQdFRD

**System (please complete the following information):**
 - Hardware: Raspberry Pi 3B
 - OS: Libreelec 9.2.4
 - Jellyfin Version: 10.6.4 (via Docker, from jellyfin/jellyfin
 - Kodi Version: Kodi 18.8.0
 - Addon Version: v0.6.3+py2
 - Playback Mode: Native

**Additional context**
Videos are stored on an external HDD with its own power supply.
The addon used to also cause some heavy stuttering, although as of a couple of days ago, lowering the "sync threads"
 option from 3 to 1, this seems to have disappeared.

**Comment by oddstr13** [comment] 2020-11-16 08:59
I don't see anything interesting in the logs (tho, I have not read all 65MB).
The kernel logs on the Pi are likely to be more interesting (in particular, look for the OOM killer…)

**Comment by oddstr13** [comment] 2021-02-01 07:39
Closing due to no follow-up.

Reopen or comment if the issue is still present, and you have more information.

**Closed by oddstr13** 2021-02-01 07:39 UTC
