### ISSUE TITLE
Websockets not working with IPv6

### ISSUE THREAD

**Issue by Ludo444** [jellyfin/jellyfin-kodi#151] opened 2019-11-29 20:16 UTC
There seems to be a bit of issue with connecting to Jellyfin websockets. Currently for me it's working correctly only for IPv4.

Also addon seems to be connecting to different websocket endpoint compared to web interface.

In web it's ```ws://SERVER_NAME/socket``` and Kodi addon reaches to ```ws://SERVER_NAME/embywebsocket```

**Logs**
```
NOTICE: JELLYFIN.jellyfin.core.ws_client -> INFO::resources/lib/jellyfin/core/ws_client.py:48 Websocket url: ws://{jellyfin-server}/embywebsocket?api_key={jellyfin-token}&device_id=***
NOTICE: JELLYFIN.jellyfin.core.ws_client -> ERROR::resources/lib/jellyfin/core/ws_client.py:65 [Errno -9] Address family for hostname not supported
```

**System (please complete the following information):**
 - OS: Debian 10
 - Jellyfin Version: 10.4.2
 - Kodi Version: 18.4
 - Addon Version: 0.3.6

**Comment by mcarlton00** [comment] 2019-12-11 02:37
`/embywebsocket` is the old one from pre-fork.  It's still been working up to this point, but I'm pretty sure the server guys changed it a while back.  I can verify and update that easily enough.  But that's not the root cause in this case.

This sounds similar to #79, so maybe it can be fixed in a similar way.  Note that the actual fix is in #109, not the PR linked in that issue.

**Comment by Ludo444** [comment] 2019-12-11 08:13
In this case, it seems it detects ipv6 correctly but refusing to connect as non-supported address family. I didn't investigate to the great detail since my home network is not ipv6 only, but maybe it would be worth to update the bundled websocket lib? Not sure how up to date it is.

There seem to be a few ipv6 issues with that lib over years, but overall probably working
https://github.com/websocket-client/websocket-client/issues?utf8=✓&q=ipv6

**Comment by mcarlton00** [comment] 2020-03-28 04:00
The version of websocket in the addon right now it pretty ancient.  While investigating another issue I made a test build with a newer release.  It might end up solving this issue as well if that's the case.  Feel free to try it out and report back. https://github.com/mcarlton00/jellyfin-kodi/archive/upgrade-websocket.zip

**Comment by Ludo444** [comment] 2020-03-29 11:35
I can confirm that the upgraded websockets library solves the ipv6 issue.

**Comment by mcarlton00** [comment] 2020-03-29 14:06
Thanks for confirming.  I'm working on a way to repackage the addon so we can pull in upstream as a dependency, but it might be a while before that makes it into an official release.

**Closed** 2021-05-03 01:16 UTC
Labels: bug
