### ISSUE TITLE
Errors on start and video playback

### ISSUE THREAD

**Issue by renrengo** [jellyfin/jellyfin-kodi#655] opened 2022-06-02 00:33 UTC
**Describe the bug**
After installing the add on, an error will pop up when trying to play a video. Restarting Kodi will produce the same error both at start and when trying to play a video.

**To Reproduce**

1. Install add-on
2. Select automatically detected server and configure
3. Errors pop up when trying to play a video

**Expected behavior**
Videos start playing

**Logs**

```
2022-06-01 15:54:22.110 T:12748   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/service.py", line 57, in <module>
                                                       LOG.info("-->[ service ]")
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/lazylogger.py", line 17, in __getattr__
                                                       from .loghandler import getLogger
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 130, in <module>
                                                       __LOGGER.addHandler(LogHandler())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 47, in __init__
                                                       self.sensitive['Server'].append(server['address'].split('://')[1])
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2022-06-01 15:54:22.349 T:12748    INFO <general>: Python interpreter stopped
2022-06-01 15:54:26.167 T:12749    INFO <general>: CPythonInvoker(1, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/service.xbmc.versioncheck/resources/lib/runner.py): script successfully run
2022-06-01 15:54:26.207 T:12749    INFO <general>: Python interpreter stopped
2022-06-01 15:54:27.315 T:12684    INFO <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2022-06-01 15:54:29.882 T:12773    INFO <general>: initializing python engine.
2022-06-01 15:54:30.625 T:12773   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'IndexError'>
                                                   Error Contents: list index out of range
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/default.py", line 18, in <module>
                                                       LOG.debug("--->[ default ]")
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/lazylogger.py", line 17, in __getattr__
                                                       from .loghandler import getLogger
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 130, in <module>
                                                       __LOGGER.addHandler(LogHandler())
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/jellyfin_kodi/helper/loghandler.py", line 47, in __init__
                                                       self.sensitive['Server'].append(server['address'].split('://')[1])
                                                   IndexError: list index out of range
                                                   -->End of Python script error report<--
                                                   
2022-06-01 15:54:30.741 T:12773    INFO <general>: Python interpreter stopped
2022-06-01 15:54:30.762 T:12684   ERROR <general>: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.jellyfin/7ee50e8bf88192abae8279e3d1946536/?filename=86+Eighty+Six+-+S01E01.mkv&id=a3361784f07c89071a32c83f6abf5c61&dbid=3191&mode=play]
```

**System (please complete the following information):**
 - OS: Fire OS 7 (Fire TV Cube)
 - Jellyfin Version: 10.7.7
 - Kodi Version: 19.4
 - Addon Version: 0.7.8 (also tried 0.7.7)
 - Playback Mode: Add-On

**Additional context**
The library does sync properly and JellyCon works fine.

**Comment by mcarlton00** [comment] 2022-06-02 12:24
Looks to be a duplicate of #654.  Include `http://` or `https://` in your server connection string as a workaround

**Closed by mcarlton00** 2022-06-02 12:24 UTC
Labels: duplicate

**Comment by renrengo** [comment] 2022-06-02 18:43
> Looks to be a duplicate of #654. Include `http://` or `https://` in your server connection string as a workaround

It's not. By default, the auto filled version includes http:// already. I also tried manually entering it with http:// and the same error occured. https is not enabled on the server.

**Comment by oddstr13** [comment] 2022-06-02 23:33
The stacktrace listed here is due to *a* server in the addon settings being without the protocol prefix.

https://github.com/jellyfin/jellyfin-kodi/blob/2a8b06a911d6334339537ad0e988607448c44db9/jellyfin_kodi/helper/loghandler.py#L41-L47

The same error, among others, is indeed present in the logs on #654.

I have not checked, but I think it could be possible setting the server address setting in the server incorrectly, and the client would use that, possibly overriding the workaround.

That, or you didn't reset the kodi addon settings, and the old, invalid entry is still present.

**Comment by renrengo** [comment] 2022-06-03 01:26
I'm uninstalling the add on and clearing its data in between attempts to change the server info since the settings are all greyed out anyway. I've even cleared out Kodi's library in between attempts, and it'll resync the libraries fine but will error out on playback.

I don't think it has anything to do with the server since JellyCon using the same server IP on the same Kodi install works fine, and multiple other clients on different devices work fine. This is a simple LAN setup.

**Comment by mcarlton00** [comment] 2022-06-03 12:55
Just so it's clear why we're saying it's the server string, this is where the error is happening:

```
server['address'].split('://')[1]
```

Line 47 in the snippet oddstr posted.

It's looking at the server address being pulled from the data file, splitting it on `://`, and then trying to take the first index of that.  So assuming you have `http://192.168.0.100:8096` as your server address, that would spit out the `192.168.0.100:8096`.  But what's happening is that your server string doesn't contain `://`, which indicates that it doesn't have http(s) either.  So when we try to take the first index of that, it's failing because there is no first index.

It seems like an extra entry has gotten added to your json cache file, and it maybe isn't getting cleared when you clear addon data for some reason.

If this is a device you have filesystem access on, you may want to check the contents of the file directly.  Find the userdata directory for your device [here](https://kodi.wiki/view/Userdata#Location), and then you're looking for `addon_data/plugin.video.jellyfin/data.json` inside of it.

**Comment by renrengo** [comment] 2022-06-03 19:06
I can confirm the addon data folder is being completely deleted between reinstalls, and the data.json and settings.xml both show the address as http://192.168.1.xxx:8096 after setting it up.

At this point I give up and I'm just going to use JellyCon.
