### ISSUE TITLE
Unable to seek properly

### ISSUE THREAD

**Issue by fakeid30** [jellyfin/jellyfin-kodi#137] opened 2019-11-05 09:29 UTC
**Describe the bug**
When trying to do a seek in Kodi , the seek only happens for 10 sec no matter how many seconds I seek.

**To Reproduce**

1. Go to 'Kodi'
2. Click on 'a movie'
3. Scroll down to 'seek'
4. See error : seeking is not happening at the time you want it to seek to

**Expected behavior**
Able to seek where I want to.

**Logs**
https://gist.github.com/fakeid30/ebf54a648557158bc5fdf84d346426bc

**System (please complete the following information):**
 - OS: Windows
 - Jellyfin Version: 10.4.1
 - Kodi Version: 18.4
 - Addon Version: 0.3.5

**Comment by oddstr13** [comment] 2019-11-08 10:42
I'm unable to reproduce on:
 - OS: Linux Mint
 - Jellyfin Version: 10.4.1
 - Kodi Version: 18.4
 - Addon Version: master (no relevant changes since 0.3.5)

Does this happen with all media, or just some?
Does seeking in Kodi work for local media?

**Comment by fakeid30** [comment] 2019-11-09 15:22
@oddstr13 it does not happen on anything except on jellyfin. And this issue is windows only I believe.

**Comment by TrueTechy** [comment] 2019-11-23 14:52
So I tried this on Windows using Kodi 18.5 and addon version 0.3.6 and seeking worked fine over multiple minutes. I take it you've tried different videos to see it's not a content specific issue? Maybe try updating your systems to see if that fixes the problem.

**Comment by fakeid30** [comment] 2019-11-24 12:58
I will update to Kodi 18.5 and let you know.

**Comment by zsmbrvr** [comment] 2019-12-18 19:02
I have the same issue on Windows 10 64bit Kodi 18.5 and addon version 0.3.6.

**Comment by TrueTechy** [comment] 2020-03-02 21:15
Have had no reports that this is still an issue and I've never experienced this issue myself. Will close this for now and if it happens again we can try to narrow down the circumstances which triggers it and how to remedy it

**Closed by TrueTechy** 2020-03-02 21:15 UTC
Labels: question

**Comment by siz-** [comment] 2020-09-21 21:31
Same thing is happening for me, resume from mm:ss doesn't work either. It works using Android on my phone.

Raspberry pi 4
LibreELEC 9.2.5
Kodi 18.8
Jellyfin addon 0.6.2+py2
Jellyfin server 10.6.4 for windows

**Comment by disconn3ct** [comment] 2020-11-11 15:06
"Me too" but I can maybe add a little info.

The environment is a kubernetes cluster (k3s on 3x pi4b, with one configured for hardware transcoding.)
If I access it directly (via MetalLB Loadbalancer) it works normally. If I access it through Traefik (v1.7) it behaves as described above, and some 4k streams won't play video at all (they play as an audio track.)
The one workaround, for streams that do play but don't seek, is to pick 'Jellyfin transcode'. The responsiveness goes way down (as expected) but it plays and seeks normally. I spot-checked it and it was only repacking, but that might have just been that one video.

**Comment by zsmbrvr** [comment] 2020-11-11 15:57
I can confirm that I also have a reverse proxy  / accessing via domain.

This could be the issue!

**Comment by mcarlton00** [comment] 2020-11-11 16:55
If you are experiencing problems with a reverse proxy, which one are you using?  I can't replicate this when using nginx

**Comment by zsmbrvr** [comment] 2020-11-11 18:31
Hmm... **I must apologize!**

I NO LONGER have this issue. The reverse proxy is nginx! It's been so long, that I have given up on the idea...

@disconn3ct , can you try nginx?

**Comment by disconn3ct** [comment] 2020-11-11 23:11
ingress-nginx works here too. Good find!

**Comment by zsmbrvr** [comment] 2020-11-11 23:27
So it's Traefik's and maybe Caddy's fault? Should report to them.

**Comment by allthesebugsv2** [comment] 2020-12-22 12:21
Anyone found a solution to this? I am using 
```
Raspberry pi 4
LibreELEC 9.2.6
Kodi 18.9
Jellyfin addon 0.6.5 in addon mode
Jellyfin server 10.6.4 running in a docker container on linux (official image)
```
Note that I also tested with Kodi running on Linux and same problem: seeking and resuming does not work behind a reverse proxy (caddy) but works fine without. And as reported above seek/resume will work when forcing a transcode.

Note that seeking and resuming works fine in the web interface also behind the reverse proxy. So I am not sure where the problem is coming from, i.e. if the problem comes with the Kodi addon or the reverse proxy

**Comment by zsmbrvr** [comment] 2020-12-22 12:29
@allthesebugsv2 you need to report to caddy. It's their issue, since it works as expected without reverse proxy or with nginx.

**Comment by allthesebugsv2** [comment] 2020-12-22 19:23
@zsmbrvr 
While writing up my massive bug report for caddy I went through my caddy configuration line by line and found the issue:
`encode zstd gzip`
This is supposed to compress the server data (in this case Jellyin's data). Removing this line made seek and resume work on the Kodi client! I also narrowed it down to
`encode gzip`
being the culprit.
Just using 
`encode zstd`
works fine.

I think I read somewhere that jellyfin 10.7 comes with its own gzip/zstd compression. Hope this does not lead to the same problem though.

**Comment by zsmbrvr** [comment] 2020-12-22 20:41
Great news! I guess that's what you get for copying a config file off the internet. 

Even if there's an issue with gzip and 10.7 at least the devs will know how to fix it.

**Comment by siz-** [comment] 2021-04-02 21:40
Thanks, removing the line worked, seeking works again :)

However for resuming, jellyfin in kodi doesn't save the current time to resume from.
It always resumes from scratch, but if you play a video using the android app or browser and stop a video, kodi will resume from that point, even if you choose "start from beginning".
