### ISSUE TITLE
Library disappears regularly

### ISSUE THREAD

**Issue by axelsimon** [jellyfin/jellyfin-kodi#480] opened 2021-03-07 16:34 UTC
**Describe the bug**
I often return to my kodi box to find that my entire library of movies and tv shows managed by Jellyfin is empty.
To fix this, I need to go into Jellyfin > Update libraries > pick "all" (or movies, or tv shows) and launch a rescan.
This might take anywhere between 3 and 15 minutes.

It makes using Jellyfin as a source completely unreliable and, furthermore, makes Kodi hardly usable for the rest of my household  (i don't want to have to explain that, sometimes, you need to go into an weird submenu to just be able to see the films that were there 30 minutes before).

I suspect this may have to do with jellyfin-kodi not being able to reach the jellyfin server and reaching the conclusion that the items in the library are all gone.

**To Reproduce**
1. Install Jellyfin-kodi
2. Log in to a server and add some libraries
3. Wait
4. Find libraries missing and in need of manual resync

**Expected behavior**
Libraries shouldn't simply wholly disappear.

**Logs**
<details><summary>kodi.log excerpt</summary>

```
2021-03-06 14:51:30.527 T:3339711360  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:241 Found Servers: []
2021-03-06 14:51:30.535 T:3339711360  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:180 connect has 1 servers
2021-03-06 14:51:30.539 T:3339711360  NOTICE: JELLYFIN.jellyfin.connection_manager -> INFO::jellyfin_kodi/jellyfin/connection_manager.py:155 begin connectToServer
2021-03-06 14:51:30.547 T:3339711360  NOTICE: JELLYFIN.jellyfin.api -> INFO::jellyfin_kodi/jellyfin/api.py:393 Sending get request to system/info/public
2021-03-06 14:51:30.577 T:3913253760  NOTICE: VideoInfoScanner: Starting scan ..
2021-03-06 14:51:30.581 T:3913253760  NOTICE: VideoInfoScanner: Finished scan. Scanning for video info took 00:00

…


2021-03-06 16:15:47.546 T:3339711360  NOTICE: JELLYFIN.entrypoint.service -> INFO::jellyfin_kodi/entrypoint/service.py:257 [ LibraryChanged ] {u'FoldersAddedTo': [u'a6d6ff82bb3ce7c990fb6ada52267cc4', u'f8a9fd7fccacb3a6cd90cf3d4d199ea9', u'1
f45aa719dc6592b31ef202685f05945'], u'CollectionFolders': [u'7e64e319657a9516ec78490da03edccb', u'9d7ad6afe9afa2dab1a2f6e00ad28fa6', u'4e985111ed7f570b595204d82adb02f3', u'db4c1708cbb5dd1676284a40f2950aba', u'767bffe4f11c93ef34b805451a696a4e
', u'0e2435875a54484cedeb48027980929f'], u'ItemsRemoved': [], u'ItemsUpdated': [], u'FoldersRemovedFrom': [], u'ItemsAdded': [u'a90f484871244c8a552d2a65eda3fc2c', u'0dc3072a1490864ba939b5453af37de3'], u'IsEmpty': False}
2021-03-06 16:15:47.561 T:3339711360  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:564 ---[ updated:2 ]
2021-03-06 16:15:48.324 T:3218404224  NOTICE: JELLYFIN.library -> INFO::jellyfin_kodi/library.py:218 -->[ q:download/3188350896 ]
2021-03-06 16:15:51.358 T:3000980352  NOTICE: JELLYFIN.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:124 500 Server Error: Internal Server Error for url: http://{jellyfin-server}/Users/2fef60e8be924235acee499c86679829/Items?Fields=
Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummary%2CEtag%2CShortOve
rview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio&Ids=a90f484871244c8a552d2a65eda3fc2c%2C0dc3072a1490864ba939b5453a
f37de3
2021-03-06 16:15:51.371 T:3000980352  NOTICE: JELLYFIN.jellyfin.http -> ERROR::jellyfin_kodi/jellyfin/http.py:147 --[ 500 response ] 500 Server Error: Internal Server Error for url: http://{jellyfin-server}/Users/2fef60e8be924235acee499c866
79829/Items?Fields=Path%2CGenres%2CSortName%2CStudios%2CWriter%2CTaglines%2CLocalTrailerCount%2COfficialRating%2CCumulativeRunTimeTicks%2CItemCounts%2CMetascore%2CAirTime%2CDateCreated%2CPeople%2COverview%2CCriticRating%2CCriticRatingSummar
y%2CEtag%2CShortOverview%2CProductionLocations%2CTags%2CProviderIds%2CParentId%2CRemoteTrailers%2CSpecialEpisodeNumbers%2CMediaSources%2CVoteCount%2CRecursiveItemCount%2CPrimaryImageAspectRatio&Ids=a90f484871244c8a552d2a65eda3fc2c%2C0dc3072
a1490864ba939b5453af37de3
2021-03-06 16:15:51.397 T:3000980352  NOTICE: JELLYFIN.downloader -> ERROR::jellyfin_kodi/downloader.py:334 'NoneType' object has no attribute '__getitem__'
                                            Traceback (most recent call last):
                                              File "jellyfin_kodi/downloader.py", line 321, in run
                                                for item in result['Items']:
                                            TypeError: 'NoneType' object has no attribute '__getitem__'
2021-03-06 16:15:52.412 T:3000980352  NOTICE: JELLYFIN.downloader -> INFO::jellyfin_kodi/downloader.py:305 --<[ q:download/3188350896 ]
```

</details>

**Screenshots**
N/A

**System (please complete the following information):**
 - OS: NixOS 20.09
 - Jellyfin Version: 10.0.6
 - Kodi Version: 18.9.0
 - Addon Version: plugin.video.jellyfin v0.7.0+py2
 - Playback Mode: add-on (i believe)

**Additional context**
N/A

**Comment by mcarlton00** [comment] 2021-03-08 22:45
Being unable to reach the server won't have this effect.  If it can't reach the server, it just does nothing.  We only remove items from the library when explicitly asked, or when the server tells us an item has been removed.  I suspect you're actually running into #409.  Something is probably triggering "Clean Library" in your system and it's wiping out your content.  There's a Kodi setting that does this, or sometimes it could be an another addon (we know the netflix addon does this to some extent).

**Comment by axelsimon** [comment] 2021-03-08 23:49
Thanks a lot for this explanation, @mcarlton00! That makes _a lot more sense_. I'd never properly set up the native kodi libraries on this box, but in preparation of doing so, i'd pre-installed the (otherwise very useful) Watchdog add-on.
I've just disabled it, we will see if it was the culprit. Otherwise i'll have a look, as the only logical thing is something triggering a library clean.

**Comment by oddstr13** [comment] 2021-03-09 22:10
Duplicate of #409

**Closed by oddstr13** 2021-03-09 22:10 UTC
