### ISSUE TITLE
How can I manually trigger sync, without reconfiguring the whole addon ?

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#459] opened 2021-01-02 14:30 UTC
Hi,

I love this addon but sometimes I have issues with sync not working correctly. So far the only way I found to manually trigger it is to reinstall the full addon and re-sync everything. It's long. Is there a way to manually trigger the sync feature ?

Thanks in advance for any answer

**Comment by mcarlton00** [comment] 2021-01-02 16:11
What issues with the sync are you having?  Better to find the root cause than have to use a workaround all the time.

That said, there's 2 methods to run an update.  Addons -> Video Addons -> Jellyfin.  You should be able to highlight a library and go into the context menu (right click or "c" on the keyboard) and select either Update or Repair.  Repair will erase the local content and sync it all fresh, while Update should only check the server for new content.

**Comment by spirillen** [comment] 2021-02-12 15:23
I have the exact same issue on two devices, every 1 to 3 days, the sync fails

And while I'm here about the sync, then every time I have shutdown/rebooted a device `Kodi sync queue` is disabled (Leia)

&

`Kodi Sync Queue` on jelyyfin is unable to install version 6.0.0, there is only the circle that keeps circling

![image](https://user-images.githubusercontent.com/44526987/107786685-7bfd3300-6d4e-11eb-86f7-ffc3263cd749.png)
![image](https://user-images.githubusercontent.com/44526987/107786774-8fa89980-6d4e-11eb-822d-7e5d05346de7.png)

**Comment by LeVraiRoiDHyrule** [comment] 2021-02-12 15:27
Hi, I don't think we are talking about the same thing.

The Jellyfin plugin "Kodi sync queue" is optionnal to reduce sync time.

I also know why you can't install it, it has nothing to see with the kodi addon.
You are using Jellyfin 10.6, and the v6 of the addon is made for Jellyfin 10.7. **Try again with the previous version of the addon, it should installs correctly.**

The last version of most of the addons from the official Jellyfin repo are for 10.7.

**Comment by spirillen** [comment] 2021-02-12 18:20
> The Jellyfin plugin "Kodi sync queue" is optionnal to reduce sync time

Was a side note... It's not directly related to this topic, but yet there are all three related as a hole, that why I mentioned it here :smiley: 

Thanks for the note about the v5 & v6 of the sync module :wave:

**Comment by mcarlton00** [comment] 2021-02-13 19:31
New media/updated status is added to Kodi in one of two ways.

* New content added/updated to server when Kodi is not running: When Kodi starts, it reaches out to the plugin and says "give me all updated content from $DATE" which is the last time it checked in with the server. Any new content, watched status updates, etc will be synced at this time. This requires the Kodi Sync Queue plugin to be installed in the server.
* New content added/updated to server when Kodi is running: The server pushes out notifications and Kodi will process and add it to it's local library immediately. This happens over a websocket connection and shouldn't involve any other extra steps or requests.

So it might be helpful to narrow down exactly when your sync failures are happening

**Closed** 2021-04-08 20:18 UTC
Labels: support
