### ISSUE TITLE
Unable to fetch the libraries

### ISSUE THREAD

**Issue by drissslim** [jellyfin/jellyfin-kodi#97] opened 2019-09-29 11:27 UTC
**Describe the bug**
Using the 0.3.0 version of the plugin with a fresh installation. I'm not able to fetch the libraries. This worked fine before with the 0.2.1

**To Reproduce**
You need to start using a fresh install and not updated version of the jellyfin kodi plugin.

**Expected behavior**
Fetch all libraries when selecting all. But no library is displayed.

**Logs**

**Screenshots**

**System (please complete the following information):**
 - OS: Android TV
 - Jellyfin Version: 10.3.7
 - Kodi Version: 18.3
 - Addon Version: 0.3.0

**Additional context**

**Comment by mcarlton00** [comment] 2019-09-29 15:29
0.3.2 was pushed out yesterday, can you try updating and see if the problem still exists?

**Comment by drissslim** [comment] 2019-09-29 16:02
I'm still getting the same issue. Even after reinstalling the plugin in version 0.3.2

**Comment by mcarlton00** [comment] 2019-09-29 21:29
I've received a similar report in Matrix for an Nvidia Shield and was just able to replicate it on my HTC (Running Android 7).  Authenticated to the server, but unable to browse/sync libraries to the local device.

Logs from montery on Matrix:
https://drive.google.com/file/d/1kIhSvhA5UJHSH6ixBA3Peg9iZnqpWgVw/view?usp=sharing

**Comment by bwaddington** [comment] 2019-09-29 22:51
Describe the bug
Using the 0.3.2 version of the plugin. I'm not able to update the libraries. 

Expected behavior
upate all libraries

System (please complete the following information):

    OS: windows
    Jellyfin Version: 10.3.7
    Kodi Version: 18.4
    Addon Version: 0.3.2

    OS: dietpi
    Jellyfin Version: 10.3.7
    Kodi Version: 18.2
    Addon Version: 0.3.2

**Comment by TrueTechy** [comment] 2019-09-29 22:54
@bwaddington can you post your kodi.log file after you've tried to update the libraries?

**Comment by bwaddington** [comment] 2019-09-29 23:03
[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/3668226/kodi.log)

**Comment by aoc** [comment] 2019-09-30 14:52
I'm experiencing a similar problem. I updated to 0.3.2, performed a local database reset to start from scratch.

Eventually I can see and play the media if I go to `Add-ons -> Video Addons -> Movies (dynamic)`. But Kodi's `Movies` and `TV Shows` sections remain empty.

I see some errors in the log but I'm not sure if they're related:
http://paste.kodi.tv/ivazanokiz

**Comment by aoc** [comment] 2019-09-30 15:46
I'm experiencing a similar problem. I updated to 0.3.2, performed a local database reset to start from scratch.

Eventually I can see and play the media if I go to Add-ons -> Video Addons -> Movies (dynamic). But Kodi's Movies and TV Shows sections remain empty.

I see some errors in the log but I'm not sure if they're related:
http://paste.kodi.tv/ivazanokiz

**Comment by TrueTechy** [comment] 2019-09-30 15:49
Hi there, we have a code change that should fix this issue, it will be part of the next release. It looks like the python for Android doesn't work quite the same as for kodi on other devices so we've implemented a fix for this

**Comment by aoc** [comment] 2019-09-30 15:57
> Hi there, we have a code change that should fix this issue, it will be part of the next release. It looks like the python for Android doesn't work quite the same as for kodi on other devices so we've implemented a fix for this

thanks! Let me know if I can help testing or providing additional info

**Comment by oddstr13** [comment] 2019-09-30 19:07
> thanks! Let me know if I can help testing or providing additional info

You should be able to test the changes by downloading https://github.com/jellyfin/jellyfin-kodi/archive/master.zip and doing install addon from zip.

**Comment by docfactory37** [comment] 2019-10-03 14:36
Also let me know if you need help testing this as got the same issue.

**Comment by docfactory37** [comment] 2019-10-03 21:38
I have test the file provide to @oddstr13, and it is working as it should shows all library's and syncs all contents and tested playback.

**Comment by aoc** [comment] 2019-10-04 00:09
I can confirm it's working fine for me too

Kodi 18.4
Android TV (7)

**Comment by mcarlton00** [comment] 2019-10-04 23:53
This has been fixed in version 0.3.3, which is available in the addon repo now

**Closed by mcarlton00** 2019-10-04 23:53 UTC
Labels: bug
