### ISSUE TITLE
sync is not working with videolibrary on MySQL

### ISSUE THREAD

**Issue by thefrip** [jellyfin/jellyfin-kodi#291] opened 2020-04-26 08:59 UTC
Hello,

I have seen the answer to issue #268, but I believe there is a misunderstanding as the point is not about the Jellyfin server (which indeed will keep the read/unread information), but about combining a shared library between different devices (I have four instances of Kodi at home sharing the same db) with the Jellyfin one. In the current state, the Jellyfin Kodi plugin just stops trying to sync as it cannot find the local database and doesn't try to open the shared one.

I'd be happy to have a look at the code but would need to understand where to get started with as I don't know where the access to the db is managed.

L.

**Comment by oddstr13** [comment] 2020-04-26 10:18
The intended way to use this addon is to install it on all four Kodi instances, and sync to the same Jellyfin server.

The addon is accessing and modifying the sqlite files of the libraries directly on disk.
It does not even know what MySQL is, much less how to interact with the shared database.

**Comment by mcarlton00** [comment] 2020-05-10 17:39
Duplicate of #170.  There's no reason to use a MySQL library in combination with the JF for Kodi addon.  Jellyfin is meant to serve as the shared backend for multiple instances.

**Closed by mcarlton00** 2020-05-10 17:39 UTC
Labels: duplicate, wontfix
