### ISSUE TITLE
Kodi 21 Beta 3 | Broken Movie Library

### ISSUE THREAD

**Issue by kontell** [jellyfin/jellyfin-kodi#824] opened 2024-02-21 17:14 UTC
**Describe the bug**

Jellyfin is unable to add a movie library to Kodi Omega Beta 3. Was working fine with Beta 2 and shows are still working.

**To Reproduce**

1. Upgrade from Beta 2 to Beta 3
2. Notice that latest movies are not shown (playback did work for shown movies)
3. Repair library.
4. Movie library is empty.
5. Alternatively, on a fresh Beta 3 install attempting to add a library appears to work but the library is empty. 

**Expected behavior**

Functional movie library.

**Logs**

[kodi.log.trimmed.txt](https://github.com/jellyfin/jellyfin-kodi/files/14362749/kodi.log.trimmed.txt)
(The log consisted of the same lines repeated thousands of times, I trimmed it to get a reasonable file size.)

**System (please complete the following information):**
 - OS: Android
 - Jellyfin 10.8.13
 - Kodi Version: 21 Beta 3
 - Addon Version: [e.g. 0.7.12]
 - Playback Mode: Addon

**Comment by mcarlton00** [comment] 2024-02-21 17:28
Duplicate of #808

**Closed by mcarlton00** 2024-02-21 17:28 UTC
