### ISSUE TITLE
Movie Folders (BDMV/DVD Folder Structure) do not play in Native mode

### ISSUE THREAD

**Issue by holow29** [jellyfin/jellyfin-kodi#327] opened 2020-06-20 22:56 UTC
**Describe the bug**
When using native mode, only files will play. No movies that are in a folder structure like BDMV (Blu-Ray) or VIDEO_TS (DVD) will play. When one clicks on the thumbnail, the library view quickly reloads but no movie starts. It appears that files (like .mkv) do play, though. (Network share path therefore appears to be correctly setup.)

I enabled debug logging on the add-on, and the error I see when trying to play the movie is as follows:

**To Reproduce**
1. Setup Kodi and Kodi Jellyfin add-on
2. Run Kodi Jellyfin add-on in native mode and make sure to set network share path correctly
3. Try to play a movie - that exists in a folder structure instead of a single file (BDMV/VIDEO_TS folder vs. .iso/.mkv/etc.) over NFS - by clicking on the thumbnail in the library.

**Expected behavior**
The movie should start to play. Instead, the thumbnails quickly reload.

**Logs**

> 2020-06-16 10:47:17.631 T:15525  NOTICE: VideoPlayer::OpenFile: nfs://192.168.1.142/volume1/films/Bluray/Woodstock (1970)
> 2020-06-16 10:47:17.632 T:15596  NOTICE: Creating InputStream
> 2020-06-16 10:47:17.648 T:15596  NOTICE: Creating Demuxer
> 2020-06-16 10:47:17.650 T:15596   ERROR: Read - Error( -14, read call failed with "<0x15>" )
> 2020-06-16 10:47:17.650 T:15596   ERROR: Open - error probing input format, nfs://192.168.1.142/volume1/films/Bluray/Woodstock (1970)
> 2020-06-16 10:47:17.650 T:15596   ERROR: OpenDemuxStream - Error creating demuxer
> 2020-06-16 10:47:17.650 T:15596  NOTICE: CVideoPlayer::OnExit()
> 2020-06-16 10:47:17.652 T:15596   ERROR: Failed to close(volume1/films/Bluray/Woodstock (1970)) - close call failed with "NFS: Commit failed with NFS3ERR_ISDIR(-21)"
> 2020-06-16 10:47:17.659 T:15577   ERROR: EXCEPTION: XBMC is not playing any file
> 2020-06-16 10:47:17.741 T:15525   ERROR: Previous line repeats 1 times.
> 2020-06-16 10:47:17.741 T:15525  NOTICE: CVideoPlayer::CloseFile()
> 2020-06-16 10:47:17.743 T:15525  NOTICE: VideoPlayer: waiting for threads to exit
> 2020-06-16 10:47:17.743 T:15525  NOTICE: VideoPlayer: finished waiting
> 2020-06-16 10:47:17.765 T:15577  NOTICE: JELLYFIN.monitor -> DEBUG::jellyfin_kodi/monitor.py:100 [ xbmc: Player.OnPlay ] {
>                                                 "item": {
>                                                     "type": "unknown"
>                                                 }, 
>                                                 "player": {
>                                                     "playerid": -1, 
>                                                     "speed": 1
>                                                 }
>                                             }
> 2020-06-16 10:47:17.770 T:15577  NOTICE: JELLYFIN.objects.actions -> DEBUG::jellyfin_kodi/objects/actions.py:780 Invalid playstate update
> 2020-06-16 10:47:17.878 T:15577  NOTICE: JELLYFIN.helper.utils -> DEBUG::jellyfin_kodi/helper/utils.py:47 --[ window clear: jellyfin_play ]

**System (please complete the following information):**
 - OS: AndroidTV (Nvidia Shield TV 2015)
 - Jellyfin Version: 10.5.5 (Docker)
 - Kodi Version: 18.7
 - Addon Version: 0.5.7
 - Playback Mode: Native

**Comment by oddstr13** [comment] 2020-06-20 23:19
Duplicate of #33 

Is this only a problem with "native" mode, or also with add-on?

Looks like we're giving Kodi a directory path, but that it doesn't know what to do with it, and is expecting some sort of file from inside of the DVD/BDMV directory structure to play back these

**Closed by oddstr13** 2020-06-20 23:19 UTC

**Comment by holow29** [comment] 2020-06-20 23:25
Ah didn't see that issue. Should I comment with my logs from above or is that not necessary?

Add-On mode works if I have transcoding enabled but not if I want to DirectPlay these folders. I think it is because of https://github.com/jellyfin/jellyfin/issues/3277

Yes, that is what it seems to me as well. I saw in another part of the log (that I would need to find) that it is in the library as type 'FILE' I think...that might be completely unrelated and I have to admit I don't know what other types exist, but thought that might be something

**Comment by oddstr13** [comment] 2020-06-20 23:46
Linking the other issue here makes a link back, so it is not strictly needed, but it would be prefrerable to keep all the info in one issue.

If there is indeed a flag for specifying file or other alternatives, that could be interesting for solving the issue.
