### ISSUE TITLE
0.7.4+py3 on Kodi 19.1 -- Series split across multiple/separate folders are not merging, even after full sync, "local database reset," and a second full sync

### ISSUE THREAD

**Issue by nothing2obvi** [jellyfin/jellyfin-kodi#565] opened 2021-08-31 20:51 UTC
**Describe the bug**
Series separated amongst multiple folders are not merging within Kodi, even though they merge flawlessly within Jellyfin's web UI.

**To Reproduce**
1. Begin library sync in Kodi (let's say this is upon initial setup)
2. When a full sync has finished, shows are still separated (e.g. 12 different listings of "The Amazing Race," which is listed as only 1 listing within Jellyfin web UI.
3. Attempted "Perform local database reset" successfully. I erased the entire Kodi database and deleted cached artwork. I did not allow it to reset Jellyfin add-on settings.
4. Attempted a second sync, as I've seen suggested somewhere on Reddit.
5. Shows are still split into separate listings.

**Expected behavior**
I expected to only have one listing per series, as I experience within Jellyfin web UI.

**Screenshots**
Screen basically looks like this:
- The Amazing Race         2 eps
- The Amazing Race         4 eps
- The Amazing Race         5 eps
- Atlanta                             7 eps
- Atlanta                             2 eps
- etc.

**System (please complete the following information):**
 - OS: Android on Amazon Firestick 4K
 - Jellyfin Version: 10.7.6
 - Kodi Version: 19.2
 - Addon Version: 0.7.4+py3
 - Playback Mode: Native

**Additional context**
Just reiterating that this is not an issue in the Jellyfin web UI, Jellyfin Media Player, etc. I have also tried a full sync then hitting "Repair libraries." I have just performed a full sync and a local database reset, only this time not deleting cached artwork. I will report back with results.

**Comment by mcarlton00** [comment] 2021-08-31 22:43
Dupe of #99.  Afaik, it can't be done because of how the server assigns item IDs and how we use those IDs locally for the database keys.  And if I'm going to be blunt, there's no reason for this.  Organize your media so it's all together and easy to find.  Future you will thank me.

**Closed by mcarlton00** 2021-08-31 22:43 UTC
Labels: duplicate

**Comment by nothing2obvi** [comment] 2021-09-01 01:21
Ah, I see. Thanks for the info. All my media is spread out amongst multiple Google Drives and I use `rclone union` to combine all the folders into one directory. Since it works great in Jellyfin's web UI and and Jellyfin Media Player, not to mention is a configuration that Jellyfin supports (i.e. "Automatically merge series that are spread across multiple folders"), I could've done without the "there's no reason for this." Thanks for the help nonetheless.
