### ISSUE TITLE
Unable to retrieve libraries

### ISSUE THREAD

**Issue by Mochaka** [jellyfin/jellyfin-kodi#110] opened 2019-10-05 10:09 UTC
**Describe the bug**
After upgrading from 0.2.1 to 0.3.0/0.3.3 kodi can't connect to my libraries. Downgrading back down to 0.2.1 fixes things. I reset my Kodi instance and tried setting it up from scratch, but same issue.

**To Reproduce**
1. Install Plugin
2. Sign in to server
3. Add libraries
4. No libraries come up

**Expected behavior**

**Logs**
https://gist.github.com/Mochaka/dee3cdb77dd70f458ec2099304a90753 

I think it could be related to line 345 - Unable to retrieve libraries: 'auth.server'

**Screenshots**

**System (please complete the following information):**
 - OS: Android
 - Jellyfin Version: 10.3 / 10.4.0
 - Kodi Version: 18.4
 - Addon Version: 0.3.3

**Additional context**

**Comment by oddstr13** [comment] 2019-10-05 11:34
Duplicate of #97, fixed by #98.

This is the log from v0.3.2.
The relevant section is
```
2019-10-05 20:00:43.631 T:3021   ERROR: Exception in thread Thread-6:
                                            Traceback (most recent call last):
                                              File "/home/jenkins/workspace/Android-ARM64-Leia/tools/depends/xbmc-depends/aarch64-linux-android-21-release/lib/python2.7/threading.py", line 801, in __bootstrap_inner
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/library.py", line 101, in run
                                                if not self.startup():
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/library.py", line 325, in startup
                                                Views().get_views()
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/views.py", line 221, in get_views
                                                save_sync(self.sync)
                                              File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jellyfin/resources/lib/database/__init__.py", line 357, in save_sync
                                                with open(os.path.join(path, 'sync.json'), 'w') as outfile:
                                            IOError: could not determine default encoding
```

The error you mention is because the addon is trying to do things out of order - before loading the server settings and connecting. The exception is caught, and that function is rerun later, successfully. Logging is just a bit verbose about it.

**Closed by oddstr13** 2019-10-05 11:34 UTC
