### ISSUE TITLE
Kodi crashes when playing movies from the main menu via the context menu

### ISSUE THREAD

**Issue by allthesebugsv2** [jellyfin/jellyfin-kodi#453] opened 2020-12-24 14:17 UTC
**Describe the bug**
When playing a movie from the Kodi main menu (i.e. the start screen) via right-click context menu (either select play or open the information screen and then click play) Kodi will crash. When directly playing via left-click the movie plays fine. Entering the movies main menu entry and then using right-click or the information menu works fine.

Series seem to play fine but won't resume when started via the information screen from the main menu. When started via the information screen after entering the series main menu entry they resume fine.

**To Reproduce**
1. Directly after starting Kodi right-click a movie and select play (do NOT enter the movies main menu entry)
2. Alternatively right-click a movie and open the information screen, then select play from there.
3. Kodi crashes

**Expected behavior**
Kodi should not crash when starting movies from the main screen via the information screen and series should resume normally.

**Logs**
Here are the logs when trying to play a movie via right-click play from the main menu (right until Kodi crashes):
https://pastebin.com/E3mnujXh

**System (please complete the following information):**
```
Client 1:
Raspberry pi 4
LibreELEC 9.2.6
Kodi 18.9
Jellyfin addon 0.6.5 in addon mode
Client 2:
Arch Linux
Kodi 18.8 (flatpak)
Jellyfin addon 0.6.5 in addon mode
Server:
Jellyfin server 10.6.4 running in a docker container on debian (official image)
Using a reverse proxy (caddy)
```

I found the same problem with both clients mentioned above. Note that the reverse proxy is NOT to blame: the problem also persists when directly using jellyfin's port on the server.

**Comment by oddstr13** [comment] 2020-12-26 01:24
Except from a warning about a skipped playlist item, I don't really see anything in those logs.
Cloud be related to #443?

**Comment by oddstr13** [comment] 2020-12-26 01:50
Closing as duplicate of #443

Thank you for vital step of using the context menu for the reproduction :smiley:

**Closed** 2020-12-26 01:50 UTC
