### ISSUE TITLE
Syncing boxsets failure

### ISSUE THREAD

**Issue by geekboy01** [jellyfin/jellyfin-kodi#218] opened 2020-03-03 17:09 UTC
**Describe the bug**
When adding a movie that is part of a set it does not combine into a set within the Kodi interface even though its in a set on the JF server.
JF Server:
    BoxSetName
         Movie1
         Movie2
Kodi (after sync update):
    Movie1
    Movie2

**To Reproduce**
make sure your kodi instance is synced, then exit kodi
Add movie that should be part of a box set ( I do utilize the JF boxset plugin), verify that its a boxset in JF.
Open Kodi let it sync. You should see the new movie but its not part of the boxset. 

**Expected behavior**
The sync should combine the movies into a set within Kodi
BoxSetName
     Movie1
     Movie2

**System (please complete the following information):**
 - OS: Android, Linux
 - Jellyfin Version: 10.4.3 (docker)
 - Kodi Version: 18.1 Android, 18.5 linux
 - Addon Version: 0.4.1

**Comment by mcarlton00** [comment] 2020-03-03 17:51
So it sounds like the initial sync catches boxsets without problems, but it doesn't handle update to them while Kodi is powered off.  Is that correct?

Could be potentially related to the kodi sync queue plugin, but needs more testing first.

**Comment by geekboy01** [comment] 2020-03-03 21:32
Correct.
The initial does catch it just fine.  Only updates, so if I reset the add-on and clear the local kodi db, then reconnect the add-on again to the server it would sync the new boxset.

**Comment by TrueTechy** [comment] 2020-03-25 11:43
@mcarlton00 this fixed by your PR?

**Comment by mcarlton00** [comment] 2020-03-25 12:16
Hopefully?  But since collections in the server are bugged in 10.5 it's kinda hard to be testing it right now.

Referencing https://github.com/jellyfin/jellyfin/issues/2565#issuecomment-603708603

**Comment by auroraflux** [comment] 2020-05-23 07:08
I can confirm that as of today, May 23rd, latest stable Jellyfin server and Kodi Addon, Collections are not showing up in Kodi as Sets, regardless of whether the Kodi library "Video" settings is set or not.

**Comment by mcarlton00** [comment] 2020-05-26 22:17
This should be fixed with the release of server version 10.6 coming in the next few weeks.  I'm just waiting for the Kodi Sync Queue plugin to be made compatible so I can verify

**Comment by mcarlton00** [comment] 2020-05-30 21:07
I've confirmed this is fixed in 10.6 with an updated plugin build

**Closed by mcarlton00** 2020-05-30 21:07 UTC
Labels: bug
