### ISSUE TITLE
Wrong tv episode played on Kodi from Jellyfin web ui

### ISSUE THREAD

**Issue by TommyRush** [jellyfin/jellyfin-kodi#180] opened 2020-01-19 18:36 UTC
**Describe the bug**
Playing a tv show from Jellyfin's web ui to kodi via the play on option always plays the most recent episode instead of selected episode. If there is 10 episodes and I play the 2nd it will instead play the 10th. 

**To Reproduce**
1. Connect to kodi with the Jellyfin web ui
2. Play a tv epsiode that isn't the most recent
3. Most recent plays instead

**Expected behavior**
Selected episode should play. 

**System (please complete the following information):**
 - OS: LibreELEC 9.2
 - Jellyfin 10.4.3
 - Kodi 18.5
 - Addon Version: 0.4.0

**Comment by TrueTechy** [comment] 2020-01-19 18:42
Sounds like #49

**Comment by mcarlton00** [comment] 2020-01-19 19:03
Definitely a duplicate of 49.  It's an upstream issue with the server that we can't fix here.  That's tracked over here: https://github.com/jellyfin/jellyfin/issues/1724

**Closed by mcarlton00** 2020-01-19 19:03 UTC
Labels: duplicate
