### ISSUE TITLE
Unable to use plugin with static IP

### ISSUE THREAD

**Issue by tuimz** [jellyfin/jellyfin-kodi#118] opened 2019-10-06 19:45 UTC
**Unable to use the plugin with static IP on LibreELEC**

**To Reproduce**

1. Fresh install of LibreELEC (RPI3, Internal wifi)
2. Install latest plugin via repository
3. Everything works fine, library synced etc.
3. Set a manual static IP address
4. Reboot 
5. Unable to use Jellyfin plugin

**Logs**
```
ERROR: Control 55 in window 10025 has been asked to focus, but it can't
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.ImportError'>
                                            Error Contents: No module named ipaddress
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/default.py", line 21, in <module>
                                                from entrypoint import Events  # noqa: F402
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/resources/lib/entrypoint/__init__.py", line 10, in <module>
                                                from helper import loghandler
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/resources/lib/helper/loghandler.py", line 14, in <module>
                                                import database
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/resources/lib/database/__init__.py", line 17, in <module>
                                                from objects import obj
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/resources/lib/objects/__init__.py", line 6, in <module>
                                                from actions import Actions
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/resources/lib/objects/actions.py", line 19, in <module>
                                                from dialogs import resume
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/resources/lib/dialogs/__init__.py", line 4, in <module>
                                                from servermanual import ServerManual
                                              File "/storage/.kodi/addons/plugin.video.jellyfin/resources/lib/dialogs/servermanual.py", line 7, in <module>
                                                import ipaddress
                                            ImportError: No module named ipaddress
                                            -->End of Python script error report<--
ERROR: GetDirectory - Error getting plugin://plugin.video.jellyfin/?content_type=video
ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.jellyfin/?content_type=video) failed
```

**Screenshots**

**System (please complete the following information):**
 - LibreELEC
 - Jellyfin Version: 10.3.7
 - Kodi Version: 18.4
 - Addon Version: 0.3.4

**Comment by tuimz** [comment] 2019-10-06 19:46
For now I have "fixed" the issue by giving the RPI an IP reservation which is more manageable in the long run anyway but still found it best to make an issue report :)

**Comment by TrueTechy** [comment] 2019-10-06 19:50
Are you sure this is addon version 0.3.4, the module ipaddress should've been removed in 0.3.4 as a fix since libreELEC doesn't have it by default

**Comment by oddstr13** [comment] 2019-10-06 19:55
The above log snippet must be from version 0.3.3.

**Comment by oddstr13** [comment] 2019-10-06 19:57
Duplicate of #108

**Closed by oddstr13** 2019-10-06 19:57 UTC
Labels: duplicate

**Comment by tuimz** [comment] 2019-10-06 20:18
Pretty sure it is 0.3.4 (atleast it says Jellyfin contributors, angelblue 0.3.4)

**Comment by tuimz** [comment] 2019-10-06 20:26
Ah no, my mistake, reinstalled the plugin and rebooted and now it works. Thanks!
