### ISSUE TITLE
Cinema mode plays the intro and exits marking the movie as watched

### ISSUE THREAD

**Issue by m33ts4k0z** [jellyfin/jellyfin-kodi#652] opened 2022-05-14 08:20 UTC
Using: https://github.com/crobibero/jellyfin-plugin-tmdb-trailers and having the cinema mode enabled, plays the first of the trailers and then goes back to the movie selection menu without playing the main feature. After the last update of the tmdb-trailers addon, the server is able to specify any amount of trailers to be played so its not necessairly 1. 

Logs:
https://paste.kodi.tv/dadirukixu.kodi

**Comment by mcarlton00** [comment] 2022-05-14 16:40
Duplicate of #549

**Closed by mcarlton00** 2022-05-14 16:40 UTC
Labels: duplicate
