### ISSUE TITLE
Consistent sync error on Kodi 19

### ISSUE THREAD

**Issue by bammerlaan** [jellyfin/jellyfin-kodi#479] opened 2021-03-07 13:46 UTC
**Describe the bug**

Hi, I'm having some trouble with getting Kodi to sync properly with my Jellyfin server. This is on a fresh install of Kodi, trying to sync music, films and tv shows. Whenever I tried syncing with Jellyfin it got stuck at some point during the sync process or gave an error saying something went wrong while syncing. On my latest attempt I tried only syncing TV shows but it still gave the "something went wrong" error. 

**To Reproduce**

1. Log into Jellyfin server
2. Let kodi sync with Jellyfin using the default options
3. During the sync process it stops and says something went wrong with the sync process. (It also still says to report errors on the Jellyfin for Kodi forums, which I read is no longer the preferred way to report issues. Maybe that should be addressed too.)

**Expected behavior**

Kodi syncs with Jellyfin and all my media shows up in the right places.

**Logs**

Attached log here:
[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/6097199/kodi.log)

By the looks of it, I'd say the relevant part is this:

```
INFO <general>: JELLYFIN.library -> ERROR::jellyfin_kodi/library.py:367 UNIQUE constraint failed: actor.name
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/objects/kodi/kodi.py", line 176, in get_person
                                                       return self._people_cache[args]
                                                   KeyError: ('Gary Cole',)
                                                   
                                                   During handling of the above exception, another exception occurred:
                                                   
                                                   Traceback (most recent call last):
                                                     File "jellyfin_kodi/library.py", line 324, in startup
                                                       sync.libraries()
                                                     File "jellyfin_kodi/full_sync.py", line 101, in libraries
                                                       self.start()
                                                     File "jellyfin_kodi/full_sync.py", line 186, in start
                                                       self.process_library(library)
                                                     File "jellyfin_kodi/full_sync.py", line 252, in process_library
                                                       media[library['CollectionType']](library)
                                                     File "jellyfin_kodi/helper/wrapper.py", line 41, in wrapper
                                                       result = func(self, dialog=dialog, *args, **kwargs)
                                                     File "jellyfin_kodi/full_sync.py", line 350, in tvshows
                                                       obj.episode(episode)
                                                     File "jellyfin_kodi/helper/wrapper.py", line 65, in wrapper
                                                       return func(*args, **kwargs)
                                                     File "jellyfin_kodi/helper/wrapper.py", line 77, in wrapper
                                                       return func(self, item, e_item=e_item, *args, **kwargs)
                                                     File "jellyfin_kodi/objects/tvshows.py", line 341, in episode
                                                       self.add_people(*values(obj, QU.add_people_episode_obj))
                                                     File "jellyfin_kodi/objects/kodi/kodi.py", line 136, in add_people
                                                       person_id = self.get_person(person['Name'])
                                                     File "jellyfin_kodi/objects/kodi/kodi.py", line 178, in get_person
                                                       person_id = self._get_person(*args)
                                                     File "jellyfin_kodi/objects/kodi/kodi.py", line 167, in _get_person
                                                       return self.add_person(*args)
                                                     File "jellyfin_kodi/objects/kodi/kodi.py", line 162, in add_person
                                                       self.cursor.execute(QU.add_person, args)
                                                   sqlite3.IntegrityError: UNIQUE constraint failed: actor.name
```

Here is also a second log from when I restarted Kodi and the sync process got stuck again (now at 65%):
[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/6097216/kodi.log)

**Screenshots**

**System (please complete the following information):**
 - OS: Arch Linux rolling, kernel: Linux x86 64-bit version 5.11.2-zen1-1-zen
 - Jellyfin Version: 10.7.0
 - Kodi Version: 19.0-9
 - Addon Version: 0.7.0+py3
 - Playback Mode: Add-On

**Additional context**

**Comment by mcarlton00** [comment] 2021-03-07 16:15
Duplicate of #469, attempted fix apparently failed.  I'll reopen the other one.

Source of this is that Kodi 19 changed the database and now requires actor names to be unique.

**Closed by mcarlton00** 2021-03-07 16:15 UTC
