### ISSUE TITLE
Info pane displays incorrect information

### ISSUE THREAD

**Issue by Ky-0** [jellyfin/jellyfin-kodi#91] opened 2019-09-28 15:25 UTC
When using the JF for Kodi addon, I click on movie info (any movie) and for some reason it displays the incorrect information (generally it displays info for my tv episodes). Metadata is correct in my libary and all works well through any other method - its only when I use the JF for Kodi plugin that this occurs.

*System
 - Jellyfin Version: 10.3.7
 - Kodi Version: 18.4
 - Addon Version: 0.2.1

**Comment by mcarlton00** [comment] 2019-09-28 16:20
Duplicate of #53

**Closed by mcarlton00** 2019-09-28 16:20 UTC
