### ISSUE TITLE
Remote control plays wrong episode

### ISSUE THREAD

**Issue by jaredallard** [jellyfin/jellyfin-kodi#51] opened 2019-07-31 01:34 UTC
When I attempt to remote control a TV series episode from Jellyfin Web it plays the wrong version on Kodi.

**Jellyfin Version** 10.3.7
**Kodi Version**: 0.2.1

**Comment by oddstr13** [comment] 2019-07-31 10:01
Duplicate of #49

**Closed by oddstr13** 2019-07-31 10:01 UTC
Labels: duplicate
