### ISSUE TITLE
jellyfin for kodi (android) Enable sync Queue not persistant

### ISSUE THREAD

**Issue by camokarzi** [jellyfin/jellyfin-kodi#672] opened 2021-12-09 21:46 UTC
Hi.  When selecting _enable kodi sync queue_ in settings.  exit Kodi and restart the option resets to false again. Checked xml and this is intially set when selected.

**Comment by mcarlton00** [comment] 2022-08-27 18:06
This is an android specific bug thanks to power saving settings.  Duplicate of #517

**Closed by mcarlton00** 2022-08-27 18:06 UTC
Labels: duplicate
