### ISSUE TITLE
The folder structure of the folder view doesn't work as expected

### ISSUE THREAD

**Issue by Usucra** [jellyfin/jellyfin-kodi#181] opened 2020-01-21 09:14 UTC
**Describe the bug**
The Addons Folder view is showing Everything directly. And I mean EVERYTHING, it is showing a direct list of every folder, every subfolder and every file within those folders and subfolders after entering a Library instead of simply showing the usual layout.

**To Reproduce**
1. Go to "Video Addons" and enter the Jellyfin addon
2. Click on Folders and enter a Library
3. Now you will see a list of all files, folders and subfolders contained in this Library

**Expected behavior**
Normal file layout, like the web app and Android App.

**System:**
 - OS: I've tried it on Android, Manjaro Linux and Windows 10 1903 and 1909
 - Jellyfin Version: 10.4.3
 - Kodi Version: 18.5
 - Addon Version: 0.4.0

**Comment by mcarlton00** [comment] 2020-01-21 23:43
What do you define as "Normal file layout".  When I browse through the addon like that I get a similar structure to what appears in the web client.  Do you have a screenshot of the issue on your end?  I'm not seeing anything out of the ordinary

**Comment by Usucra** [comment] 2020-01-22 04:28
My view of a "normal" file listing is the Typical hierarchical folder view of any system I've worked on. You go into a folder and there are other folders/files inside and you only see them after entering the folder. Kodi just puts out a List of all files, folders and subfolders. I've also attached my log files of the Clean Kodi Install.

![Kodi](https://user-images.githubusercontent.com/32991622/72864748-719c7100-3cd5-11ea-942f-d17ffeeaf255.PNG)
![Kodi 2](https://user-images.githubusercontent.com/32991622/72865366-d8bb2500-3cd7-11ea-99a9-6863c990b7d4.PNG)
![hierarchical list](https://user-images.githubusercontent.com/32991622/72864749-719c7100-3cd5-11ea-9ef6-eb34f57e17c7.PNG)


[kodi.log](https://github.com/jellyfin/jellyfin-kodi/files/4095237/kodi.log)

**Comment by mcarlton00** [comment] 2020-01-22 14:01
What is your file structure like on the disk?  And is this a TV Shows library or a Mixed Content library in Jellyfin?  My library views match what's in the Web UI, so this is a bit of an outlier.  I'm also seeing a lot of errors in your logs that I haven't seen before, so I'm curious what's different about your setup.

**Comment by feromax** [comment] 2020-05-07 01:04
Interestingly, I have the same issue with the Jellyfin client on Fire TV (same as Android TV?):  A movie library that has a separate folder view enabled simply shows all library contents.  This is not an issue for the Jellyfin web client nor the Android client.  And when the DLNA server is enabled, VLC and Kodi connecting via upnp are able to see folder views.  (But Kodi w/the Jellyfin addon cannot -- which I believe is the issue reported above.

**Comment by mcarlton00** [comment] 2020-05-10 19:33
I wonder if this is related to the storage location found #99

**Comment by microwax** [comment] 2020-05-25 19:47
New user of Jellyfin here. I'm having exactly the same issue. I'm using the web UI (with Firefox). The folder view appears to work only at the top level of the library path - if you enter a subfolder (which contains other, nested subfolders) , then the UI assembles and shows all the media from the nested subfolders in a flat view, rather than continuing with a folder-by-folder view. I've set the type of the corresponding library to "mixed content", but to no avail.

Furthermore, in the flat view, the media files are presented and sorted by their tagged names, rather than by their actual file names.

Not everyone wants to rely on tags to sort and present their media collection. My media directories are already highly structured, and I have no interest in re-organising them, re-naming them or retagging the media. (And I don't use scrapers).

In folder view, I would just expect the directories and files to be presented in the same structure and with the same names as they're stored on disk. (And ideally displaying poster art, cover art, thumbnails etc. from pre-defined image names - folder.png, for example - stored within the respective directories).

This is how Kodi's folder view does things, and to be honest I expected it to work this way in Jellyfin too.

I have a lot of media, and displaying it all mixed up in a flat view and by tagged name kinda defeats the purpose of a folder view. For me personally, it makes Jellyfin's UI too cumbersome to use.

**Comment by mcarlton00** [comment] 2020-06-16 01:27
@Usucra unless I can find some way of reproducing this, we're going to have to close it and move on.  I've tried a variety of access methods and haven't been able to make my file list behave like yours.

* What library type is this? (TV Shows or Mixed Content)
* Is this in Addon mode or Native mode?
* Are your files all stored in one place or are they spread across multiple locations (ie: some files on one drive, some on a second drive, or stored in different locations on the same drive)

If you can turn on debug logging in the addon settings (not Kodi) that may also help.

**Comment by microwax** [comment] 2020-06-16 07:54
The underlying problem might not be in the Kodi plugin.

I don't have the Kodi plugin, but I experienced exactly the same problem as Usucra described in his initial post. In my case, I was using the web UI with Jellyfin 10.5.5. I tried library types "TV Shows" and "Mixed Content" but it made no difference - Jellyfin insisted on showing a flat view (i.e. everything from all subfolders shown on one page).

I then installed 10.4.3, and the issue mostly went away, but only by enabling "Prefer embedded titles over filenames" and, reluctantly, conducting an exercise to tag all my media files with titles. Nevertheless, Jellyfin still sometimes fails to display items as they are arranged on disk (especially if the filename or title tags contain digits, which it often misinterprets as season numbers).

I haven't looked at the code, but I get the feeling that Jellyfin's underlying approach is to always parse the metadata (title) or media path and try to extrapolate the TV show name, the season, the year of production etc, and then to arrange the library accordingly. But it sometimes gets this wrong, leading to items not being displayed as one expects (or occasionaly not displayed at all).

In my view, what is really needed is an option to say "thank you, Jellyfin, but I'm already quite organised, and for this library I would like you to arrange items with the exact filenames and structure you see on disk. Please don't try to extrapolate this information" - i.e. a "don't be clever" option. I suspect that this would resolve the behaviour I'm seeing in the web UI and the behaviour Usucra saw in the Kodi plugin.

There's a feature request for a basic folder view - [https://features.jellyfin.org/posts/224/add-a-folder-view-to-libraries] - and I've added my own findings to that thread.

**Comment by mcarlton00** [comment] 2020-06-16 12:17
It's been discussed to rip out Mixed Content and have a Custom type that doesn't do any parsing so you can have a raw folder view, but it needs a good bit of work to get to that point.  That said, as long as your stuff is named properly ([movies](https://jellyfin.org/docs/general/server/media/movies.html), [tv shows](https://jellyfin.org/docs/general/server/media/shows.html)), there should be no problem parsing things.  We can't support every naming scheme on the planet, because it just makes the whole scanning process impossible to logic through.

**Comment by microwax** [comment] 2020-06-16 13:17
I think a non-parsing custom type is a very good idea - especially as there will always be differing opinions on what constitutes proper naming and there will always be exceptions. The creation of a non-parsing view will resolve those issues and make Jellyfin a lot more usable for those affected. Kodi seems to handle raw folder views pretty well alongside its more advanced library functionality. Admittedly, Kodi is coded in a different language, but perhaps the same approach could be adapted for Jellyfin.

**Closed** 2020-10-01 00:11 UTC
Labels: upstream

**Comment by VigibotDev** [comment] 2023-05-30 17:50
Hello;
This option just add a duplicate beautiful libraries view for me, I don't get the usefull raw folder view.
Version : 10.8.10 on Debian 11, Firefox as client.
